# Generated by Django 4.1.3 on 2022-12-22 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0002_initial'),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplicationmodel',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applicant', to='authentication.studentmodel'),
        ),
        migrations.AddField(
            model_name='jobapplicationmodel',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applied', to='app.jobmodel'),
        ),
    ]
