# Generated by Django 4.1.3 on 2022-12-19 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_studentmodel_is_complete'),
        ('app', '0004_companymodel_desc'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JobApplication',
            new_name='JobApplicationModel',
        ),
        migrations.AddField(
            model_name='jobmodel',
            name='no_of_applicants',
            field=models.IntegerField(default=0),
        ),
    ]
