# Generated by Django 4.1.3 on 2022-11-22 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('baseuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('resume', models.FileField(blank=True, upload_to='resume')),
                ('headshot', models.ImageField(blank=True, upload_to='headshot')),
                ('linkedIn_link', models.URLField(blank=True, null=True)),
                ('gitHub_link', models.URLField(blank=True, null=True)),
            ],
            options={
                'db_table': 'student',
            },
            bases=('base.baseuser',),
        ),
        migrations.CreateModel(
            name='TeacherModel',
            fields=[
                ('baseuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'teacher',
            },
            bases=('base.baseuser',),
        ),
    ]
