# Generated by Django 4.1.3 on 2022-12-19 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('headshot', models.ImageField(blank=True, upload_to='headshot')),
                ('linkedIn_link', models.URLField(blank=True, null=True)),
                ('gitHub_link', models.URLField(blank=True, null=True)),
                ('skills', models.TextField()),
                ('job', models.TextField()),
                ('department', models.TextField()),
                ('bio', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='TeacherModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'teacher',
            },
        ),
    ]
