# Generated by Django 4.1.3 on 2022-12-22 16:55

import authentication.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('mybaseuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('roll_no', models.IntegerField()),
                ('bio', models.TextField(blank=True, null=True)),
                ('skills', models.TextField(blank=True, null=True)),
                ('resume', models.FileField(blank=True, upload_to='resume', validators=[authentication.validators.validate_file_extension_pdf, authentication.validators.validate_file_size])),
                ('headshot', models.ImageField(blank=True, upload_to='headshot')),
                ('linkedIn_link', models.URLField(blank=True, null=True)),
                ('gitHub_link', models.URLField(blank=True, null=True)),
            ],
            options={
                'db_table': 'student',
            },
            bases=('base.mybaseuser',),
        ),
        migrations.CreateModel(
            name='TeacherModel',
            fields=[
                ('mybaseuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'teacher',
            },
            bases=('base.mybaseuser',),
        ),
    ]
