# Generated by Django 4.1.3 on 2022-11-22 11:05

import authentication.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='resume',
            field=models.FileField(blank=True, upload_to='resume', validators=[authentication.validators.validate_file_extension_pdf, authentication.validators.validate_file_size]),
        ),
    ]
