# Generated by Django 4.1.3 on 2022-12-19 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmodel',
            name='department',
        ),
        migrations.RemoveField(
            model_name='studentmodel',
            name='job',
        ),
    ]
