# Generated by Django 4.1.3 on 2022-12-19 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_studentmodel_is_complete'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileSavingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='excel')),
            ],
        ),
    ]
