# Generated by Django 4.1.3 on 2022-12-19 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mybaseuser',
            name='is_verified',
        ),
    ]
